# configs/project_configs.yaml

Project_2:
  name: "Project 2"
  project_num: "2"
  part_a_due: "2026-02-20 23:59"
  part_b_due: "2026-02-28 23:59"
  ab_cutoff: 6
  spec_url: "https://cs61c.org/sp26/projects/proj2/"
  num_subthreads: 9
  subthreads: 
    - "Absolute Value (Walkthrough)"
    - "RELU"
    - "Argmax"
    - "Dot Product"
    - "Testing"
    - "Matrix Multiplication"
    - "Read Matrix"
    - "Write Matrix"
    - "Classify"
  logic_module: "logic.project_posting"
  template_folder: "templates/projects"